# Generated by Django 3.0.3 on 2020-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0002_auto_20200304_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
