# Generated by Django 3.0.3 on 2020-03-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
