# Generated by Django 3.0.3 on 2020-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0013_auto_20200309_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('liker_email', models.EmailField(max_length=254)),
                ('is_liked', models.BooleanField()),
            ],
        ),
    ]
