# Generated by Django 3.0.4 on 2020-03-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0014_liked_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('commenter_email', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
