# Generated by Django 3.0.4 on 2020-03-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0015_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_post',
            name='commenter_pic',
            field=models.ImageField(blank=True, default='images/blankprofile.webp', upload_to='images'),
        ),
    ]
