# Generated by Django 3.0.6 on 2020-05-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0017_auto_20200320_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
